name: bayesbay-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<=3.13
  - arviz
  - bayesbay
  - h5netcdf
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - scipy
  - umap-learn
